import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from postgrest.exceptions import APIError

from product_agent.config import get_settings
from product_agent.schemas import Confidence, ProductIntelligence
from product_agent.storage import ProductStore


def main() -> None:
    settings = get_settings()
    store = ProductStore(settings.supabase_url, settings.supabase_key, settings.supabase_products_table)

    probe = store.client.table(settings.supabase_products_table).select("payload").limit(1).execute()
    print(f"supabase table '{settings.supabase_products_table}' reachable; rows_returned={len(probe.data or [])}")

    product = ProductIntelligence(
        manufacturer_part_number="SMOKE-TEST-001",
        brand="SmokeTest",
        title="SmokeTest SMOKE-TEST-001 Test Product",
        category="Industrial Components",
        commerce_description="Smoke test product used to verify Supabase persistence.",
        key_features=["Verifies product_agent storage save and list paths."],
        confidence=Confidence.low,
        quality_warnings=["Generated by smoke_test_supabase.py."],
    )
    try:
        store.save(product)
    except APIError as exc:
        if getattr(exc, "code", None) == "42501" or "row-level security" in str(exc).lower():
            raise SystemExit(
                "supabase smoke test failed: products table is reachable, but inserts are blocked by RLS. "
                "Use a service_role key for local backend writes or add an insert policy for your anon role."
            ) from exc
        raise

    saved = store.exact_match(product.manufacturer_part_number, product.brand)
    assert saved is not None
    assert saved.manufacturer_part_number == product.manufacturer_part_number
    assert saved.brand == product.brand

    print("supabase smoke test passed")


if __name__ == "__main__":
    main()
